name: Deploy to Dev ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: dev-orange
  push:
    branches: ["main"]

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@main
    with:
      app-name: alerts-viewer
      environment: ${{ github.event.inputs.environment || 'dev-orange' }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
